repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.17.0"
    hooks:
      - id: terraform-docs-system
        args: ["."]
        types: []
        types_or: [markdown, terraform]

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.44'
    hooks:
      - id: checkov
        args: ["--skip-path", "tests"]
      - id: checkov_secrets
